server:
  port: 8083
spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/fashion_product_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
app:
  seed:
    enabled: ${PRODUCT_SEED_ENABLED:true}
    product-data-path: ${PRODUCT_SEED_FILE:}
