server:
  port: ${PRODUCT_SERVICE_PORT:8083}

spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/fashion_product_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:${MYSQL_ROOT_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:${EUREKA_PORT:8761}/eureka/}

app:
  seed:
    enabled: ${PRODUCT_SEED_ENABLED:false}
    product-data-path: ${PRODUCT_SEED_FILE:}
