spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3308/fashion_store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:devuser}
spring.datasource.password=${DB_PASSWORD:devpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:VGhpc0lzQVNlY3VyZVNlY3JldEtleUZvckpXVEF1dGhUaGF0SXNBdExlYXN0MzJC}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

app.google.client-id=${GOOGLE_CLIENT_ID:621246077172-7ts8o98eoo29umosaeqkohh5udl9hfht.apps.googleusercontent.com}

app.email-verification.otp-expiration-minutes=${EMAIL_VERIFICATION_OTP_EXPIRATION_MINUTES:10}
app.mail.from=${MAIL_FROM:no-reply@fashion-store.local}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:nhocng97@gmail.com}
spring.mail.password=${MAIL_PASSWORD:lgkswqaemdzdlrhb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
